import{PokemonList} from './Pokemon.model';

export const POKEMON_LIST: PokemonList = [
  {
    id: 1,
    name: 'Bulbizare',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png',
    life: 25,
    damage: 5,
    types: ['plante','posson'],
    created: new Date('2022-01-01'),
  },
  {
    id: 2,
    name: 'salameche',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png',
    life: 28,
    damage: 6,
    types: ['plante','posson'],
    created: new Date('2022-01-01'),
  },
  {
    id: 3,
    name: 'Carapuce',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png',
    life: 28,
    damage: 6,
    types: ['plante','posson'],
    created: new Date('2022-01-01'),
  },
  {
    id: 4,
    name: 'Aspicot',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png',
    life: 16,
    damage: 2,
    types: ['Insecte','posson'],
    created: new Date('2025-11-18'),
  }, {
    id: 5,
    name: 'Roucool',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png',
    life: 30,
    damage: 7,
    types: ['Normal','vol'],
    created: new Date('2025-11-18'),
  },
  {
    id: 6,
    name: 'Rattata',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png',
    life: 18,
    damage: 6,
    types: ['Normal'],
    created: new Date('2025-11-18'),
  },

  {
    id: 7,
    name: 'Piafabec',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png',
    life: 14,
    damage: 5,
    types: ['Normal','vol'],
    created: new Date('2025-11-18'),
  },
  {
    id: 8,
    name: 'Abo',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png',
    life: 16,
    damage: 4,
    types: ['Poisson'],
    created: new Date('2025-11-18'),
  },
  {
    id: 9,
    name: 'Pikatchu',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png',
    life: 21,
    damage: 7,
    types: ['Electrik'],
    created: new Date('2025-11-18'),
  },

  {
    id: 10,
    name: 'Sabelette',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png',
    life: 19,
    damage: 3,
    types: ['Normal'],
    created: new Date('2025-11-18'),
  },
  {
    id: 11,
    name: 'Mélofée',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png',
    life: 25,
    damage: 5,
    types: ['Fée'],
    created: new Date('2025-11-18'),
  },{
    id: 12,
    name: 'Groupix',
    picture: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png',
    life: 17,
    damage: 8,
    types: ['Feu'],
    created: new Date('2025-11-18'),
  },



];
